Delay BroadcastChannel
WICG/nav-speculation pull request #140
Opened 2022-02-15 16:23 UTC by noamr

Still requires a big WPT overhaul.

2022-02-15 21:07 UTC, jeremyroman commented
Is this sufficient? What about `message` and `messageerror` events firing? This makes pages able to receive but not send messages, and buffers outgoing messages. Is that desirable?

It's not obvious to me whether it's better to make the BroadcastChannel essentially unplugged (drop incoming and outgoing messages while prerendering), or buffered (for both incoming and outgoing messages), or something else (if we don't want it to function), but we should probably write down the reasoning for our choice.

2022-02-16 07:03 UTC, noamr commented
> Is this sufficient? What about `message` and `messageerror` events firing? This makes pages able to receive but not send messages, and buffers outgoing messages. Is that desirable?
> 
> It's not obvious to me whether it's better to make the BroadcastChannel essentially unplugged (drop incoming and outgoing messages while prerendering), or buffered (for both incoming and outgoing messages), or something else (if we don't want it to function), but we should probably write down the reasoning for our choice.

Gotcha, this is not fully thought out. Will start an issue to discuss this.

2022-02-16 08:46 UTC, noamr commented
As I mentioned in the discussion, the main reasoning for this is to avoid nonsensical behavior in one of the main cases of `BroadcastChannel`, which is to detect "other open tabs", scenarios like "we see that you've logged in from another tab, do you want to log out here?". Deferring outgoing messages can achieve that without disrupting other flows.

2022-02-24 15:11 UTC, nyaxt requested changes

2022-02-24 15:11 UTC, nyaxt commented on prerendering.bs
> +    text: ServieWorker; url: serviceworker-interface
typo: ServiceWorker

2022-02-24 15:32 UTC, merged

2022-02-24 15:40 UTC, jeremyroman commented
lgtm2 fwiw; thanks for following up